export const GUIDE_KEY = 'pigeonsub.guide.v1';
export type GuideProgress = { status: 'new' | 'paused' | 'dismissed' | 'done'; index: number };
export type GuideStep = { id: string; route: string; anchor: string; title: string; body: string; plus: string; reason: string };
export function guideSteps(subscriptionId = 1): GuideStep[] {
  const detail = `/(tabs)/subscriptions/${subscriptionId}`;
  return [
    { id: 'savings', route: '/(tabs)', anchor: 'home-summary', title: 'Comprenez ce que vous pouvez économiser', body: 'Le grand montant doré estime vos économies annuelles après résiliations confirmées. Le montant « possibles » dépend des résiliations à terminer. Touchez la carte pour voir le calcul.', plus: 'Le calcul est gratuit. Plus permet de suivre tous vos abonnements.', reason: 'limit' },
    { id: 'budget', route: '/(tabs)', anchor: 'home-budget', title: 'Fixez votre budget', body: 'La jauge compare vos dépenses actuelles au budget mensuel que vous choisissez. Un dépassement reste visible.', plus: 'Avec Plus, comparez aussi les scénarios selon vos notes et votre usage.', reason: 'stats' },
    { id: 'review', route: '/(tabs)', anchor: 'home-review', title: 'Repérez les abonnements à éviter', body: 'Les flèches parcourent les abonnements peu utilisés, mal notés ou à résilier. Le montant est celui de la prochaine échéance.', plus: 'Ce repérage est gratuit. Les simulations combinées sont incluses dans Plus.', reason: 'stats' },
    { id: 'subscriptions', route: '/(tabs)/subscriptions', anchor: 'subscription-views', title: 'Retrouvez vos abonnements', body: 'Tous vos abonnements sont ici, les plus récents en tête. Faites défiler les vues et catégories pour filtrer la liste. Le bouclier affiche les dates de sûreté, puis les trie au clic suivant. Le bouton + ouvre le formulaire.', plus: '5 abonnements actifs, essais compris, sont gratuits. Plus retire cette limite et permet d’importer une photo comme icône depuis le formulaire.', reason: 'limit' },
    { id: 'photos', route: detail, anchor: 'subscription-proofs', title: 'Gardez vos justificatifs', body: 'Ajoutez un reçu, une capture ou une preuve de résiliation. Touchez une miniature pour l’agrandir. Les photos restent sur cet appareil.', plus: '5 photos pour chacun des 5 abonnements gratuits. Plus permet davantage de photos sur tous vos abonnements.', reason: 'photos' },
    { id: 'safety', route: detail, anchor: 'subscription-safety', title: 'Agissez avant la date de sûreté', body: 'Choisissez une marge avant le renouvellement et activez le rappel depuis la fiche. PigeonSub ne résilie pas le contrat à votre place.', plus: 'Dates personnalisées et rappels sur 5 abonnements gratuits ; sur tous les abonnements avec Plus.', reason: 'safety' },
    { id: 'calendar', route: '/(tabs)/calendar', anchor: 'calendar-month', title: 'Anticipez les prochaines dates', body: 'Dans Alertes, sélectionnez un jour pour voir les échéances à partir de cette date. Orange : sûreté ; violet : prélèvement ou fin d’essai. Les icônes repèrent les abonnements.', plus: 'Le calendrier est gratuit. Plus étend le suivi et les rappels à tous vos abonnements.', reason: 'safety' },
    { id: 'trials', route: '/(tabs)/coupons?view=trials', anchor: 'offers-content', title: 'Décidez avant la fin d’un essai', body: 'Un essai reste distinct des dépenses payantes. À sa fin, confirmez si vous le conservez ou si vous avez terminé sa résiliation.', plus: 'Les essais comptent dans les 5 abonnements gratuits. Leur suivi est illimité avec Plus.', reason: 'limit' },
    { id: 'coupons', route: '/(tabs)/coupons?view=coupons', anchor: 'offers-content', title: 'Gardez les offres utiles', body: 'Enregistrez vos coupons et leurs dates limites. Les vues séparent les offres à suivre, utilisées et expirées.', plus: 'Le carnet de coupons est gratuit. Une plume indique toujours une option Plus, jamais un coupon vérifié.', reason: 'limit' },
    { id: 'stats', route: '/(tabs)/stats', anchor: 'stats-chart', title: 'Lisez vos chiffres', body: 'La courbe projette vos coûts sur 3, 6 ou 12 mois. Les catégories montrent où part votre argent ; ce ne sont pas des paiements bancaires constatés.', plus: 'Budget, projection et catégories sont gratuits. Plus ajoute les simulations avancées.', reason: 'stats' },
    { id: 'views', route: '/(tabs)/stats', anchor: 'stats-views', title: 'Comparez les budgets possibles', body: 'Ouvrez le menu des vues : après résiliations, sans les peu utilisés, sans les mauvaises notes ou une vue combinée.', plus: 'Les vues selon l’usage, les notes et la vue combinée nécessitent Plus. Une simulation ne modifie pas vos abonnements.', reason: 'stats' },
    { id: 'history', route: detail, anchor: 'subscription-history', title: 'Suivez vos décisions', body: 'Dans chaque fiche, confirmez la résiliation et conservez ses preuves. L’historique permet de retrouver les décisions successives.', plus: 'Le suivi et la confirmation sont gratuits. La consultation de l’historique est incluse dans Plus.', reason: 'history' },
    { id: 'settings', route: '/(tabs)/profile', anchor: 'premium-settings', title: 'Retrouvez le guide dans les réglages', body: 'Relancez ce guide ici, changez le thème ou exportez vos données depuis Confidentialité. La carte Premium présente les offres et la restauration des achats.', plus: 'Touchez une plume dorée pour découvrir l’option concernée. En démo, les options Plus sont ouvertes sans achat.', reason: 'settings' },
  ];
}
export function readGuideProgress(raw: string | null): GuideProgress {
  try {
    const p = JSON.parse(raw ?? 'null');
    if (p && ['new', 'paused', 'dismissed', 'done'].includes(p.status) && Number.isInteger(p.index) && p.index >= 0 && p.index < guideSteps().length) return p;
  } catch { /* A corrupt progress record must not prevent using the app. */ }
  return { status: 'new', index: 0 };
}
